name: trunk

on:
  push:
    branches: [main]

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
  #       node-version: [14.x, 16.x]
  #   runs-on: ${{matrix.os}}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{matrix.node-version}}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{matrix.node-version}}
  #         cache: yarn
  #     - name: Install Dependencies
  #       run: corepack enable && yarn install --immutable
  #     - run: yarn build
  #     - run: yarn test

  # https://github.community/t/how-can-i-test-if-secrets-are-available-in-an-action/17911/10
  checkNpmTokenSet:
    name: Check if NPM_TOKEN secret is set
    runs-on: ubuntu-latest
    outputs:
      isNpmTokenSet: ${{ steps.checkNpmTokenSet.outputs.isNpmTokenSet }}
    steps:
      - name: Check if NPM_TOKEN secret is set
        id: checkNpmTokenSet
        run: |
          echo "isNpmTokenSet: ${{ secrets.NPM_TOKEN != '' }}"
          echo "::set-output name=isNpmTokenSet::${{ secrets.NPM_TOKEN != '' }}"
      - uses: actions/checkout@v3
      - run: git tag test && git push --tags

  release-canary:
    # needs: [test, checkNpmTokenSet]
    if: needs.checkNpmTokenSet.outputs.isNpmTokenSet == 'true'
    uses: prisma-labs/dripip/.github/workflows/release.yml@master
    secrets:
      npmToken: ${{secrets.NPM_TOKEN}}
      githubToken: ${{secrets.DRIPIP_GITHUB_TOKEN}}
